name: qr_malicious_detection
description: A Flutter app for detecting malicious QR codes using TensorFlow Lite.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # TensorFlow Lite for Flutter
  tflite_flutter: ^0.11.0
  
  # Image processing
  image: ^4.1.7
  
  # Image picker for gallery/camera
  image_picker: ^1.0.7
  
  # UI
  cupertino_icons: ^1.0.6

  mobile_scanner: ^3.5.6 
  camera: ^0.10.5+5  # Alternative camera package
  permission_handler: ^11.3.0 
  qr_flutter: ^4.1.0
  qr: ^3.0.1  # Low-level QR generation
  flutter_zxing: ^2.2.1
  path_provider: ^2.1.3
  qr_code_tools: ^0.2.0

  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Add your TFLite model to assets
  assets:
    - assets/benign_sample.png
    - assets/malicious_sample.png
    - assets/models/qr_security_model.tflite
    - assets/models/model.tflite